"""empty message

Revision ID: 40d840334dc2
Revises: 487e7bafac9c
Create Date: 2023-08-15 16:43:04.285331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d840334dc2'
down_revision = '487e7bafac9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_branch', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization_branch', sa.Column('modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization_branchopeninghours', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization_branchopeninghours', sa.Column('modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization_organization', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organization_organization', sa.Column('modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reference_city', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reference_city', sa.Column('modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reference_service', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reference_service', sa.Column('modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reference_workday', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reference_workday', sa.Column('modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_workday', 'modified')
    op.drop_column('reference_workday', 'created')
    op.drop_column('reference_service', 'modified')
    op.drop_column('reference_service', 'created')
    op.drop_column('reference_city', 'modified')
    op.drop_column('reference_city', 'created')
    op.drop_column('organization_organization', 'modified')
    op.drop_column('organization_organization', 'created')
    op.drop_column('organization_branchopeninghours', 'modified')
    op.drop_column('organization_branchopeninghours', 'created')
    op.drop_column('organization_branch', 'modified')
    op.drop_column('organization_branch', 'created')
    # ### end Alembic commands ###
