"""empty message

Revision ID: 487e7bafac9c
Revises: 
Create Date: 2023-08-06 10:58:54.510563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487e7bafac9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified', sa.TIMESTAMP(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_organization',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_city',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_service',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_workday',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=11), nullable=False),
    sa.Column('short_name', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_branch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=18), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(precision=6), nullable=False),
    sa.Column('longitude', sa.Float(precision=6), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['reference_city.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_branchopeninghours',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('work_day_id', sa.BigInteger(), nullable=False),
    sa.Column('time_from', sa.SmallInteger(), nullable=False),
    sa.Column('time_to', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['organization_branch.id'], ),
    sa.ForeignKeyConstraint(['work_day_id'], ['reference_workday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_branchservice',
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['organization_branch.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['reference_service.id'], ),
    sa.PrimaryKeyConstraint('branch_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_branchservice')
    op.drop_table('organization_branchopeninghours')
    op.drop_table('organization_branch')
    op.drop_table('reference_workday')
    op.drop_table('reference_service')
    op.drop_table('reference_city')
    op.drop_table('organization_organization')
    op.drop_table('account_user')
    # ### end Alembic commands ###
